directories:
  output: dist-electron
  buildResources: build
appId: com.yourcompany.aims-accounting
productName: AIMS Accounting Software
files:
  - filter:
      - dist/**/*
      - main.cjs
      - package.json
win:
  target: nsis
mac:
  target: dmg
linux:
  target: AppImage
electronVersion: 30.5.1
